user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

bookmarks:
    type:     rest
    resource: AppBundle\Controller\BookmarkController

boxes:
    type:     rest
    resource: AppBundle\Controller\BoxController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
